version: "3"

services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    image: node-app-prod:latest
    environment:
      - NODE_ENV=production
    command: npm start
